n = "10000"
t1 = "2.7"
d_min = "3"
d_max = "100"
d_max_iter = "1000"
t2 = "2.7"
c_min = "10"
c_max = "1000"
c_max_iter = "1000"
mu = "0.2"
islocal = "false"
isCL = "false"
degreefile = "Graph_mu//useless/deg.dat"
communitysizesfile = "Graph_mu//useless/cs.dat"
communityfile = "Graph_mu//useless/com.dat"
networkfile = "Graph_mu//useless/edge.dat"
seed = ""
