from .mnmf import MNMF
from .deepwalk import DeepWalk
from .node2vec import Node2Vec
from .walklets import Walklets
from .randne import RandNE
from .diff2vec import Diff2Vec
from .boostne import BoostNE
from .netmf import NetMF
from .laplacianeigenmaps import LaplacianEigenmaps